# Generated by Django 3.2.14 on 2022-07-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variants',
            new_name='Variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='variant',
            new_name='variants',
        ),
    ]
