# Generated by Django 3.2.14 on 2022-07-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220718_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_main',
            field=models.ImageField(null=True, upload_to='images/product'),
        ),
    ]
