# Generated by Django 3.2.14 on 2022-07-17 18:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_title', models.CharField(default='Beautifully Crafted Gifts for loved ones or yourself', max_length=100)),
                ('store_name', models.CharField(default='Goreba', max_length=20)),
                ('company', models.CharField(default='Goreba', max_length=20)),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('short_description', models.CharField(blank=True, default='', max_length=50)),
                ('story_headline', models.CharField(blank=True, default='Goreba ~ Prologue', max_length=20)),
                ('story', ckeditor.fields.RichTextField(blank=True)),
                ('store_phone', models.CharField(blank=True, default='+1 (514) 258 7260', max_length=20)),
                ('store_address', models.CharField(blank=True, default='153 Cresthaven Dr. Nepean, ON, K2G 6T2 Canada', max_length=50)),
                ('store_email', models.CharField(blank=True, default='goreba99@gmail.com', max_length=20)),
                ('store_status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('MAINTENANCE', 'MAINTENANCE')], max_length=15)),
                ('store_icon', models.ImageField(blank=True, upload_to='images/goreba/')),
                ('store_photo', models.ImageField(blank=True, upload_to='images/goreba/')),
                ('order_receipt_banner', models.ImageField(blank=True, upload_to='images/goreba')),
                ('store_link_facebook', models.CharField(default='https://www.facebook.com/goreba.canada/', max_length=50)),
                ('store_link_instagram', models.CharField(default='https://www.instagram.com/goreba.canada/', max_length=50)),
                ('store_link_twitter', models.CharField(default='https://twitter.com/goreba_canada/', max_length=50)),
                ('store_link_youtube', models.CharField(default='https://www.youtube.com/channel/UCJQTNsK5_sPUic7gO0tGovw', max_length=75)),
                ('store_link_pinterest', models.CharField(default='https://www.pinterest.ca/goreba_canada/', max_length=50)),
                ('store_link_linkedin', models.CharField(default='https://www.linkedin.com/company/goreba/', max_length=50)),
                ('smtp_server', models.CharField(blank=True, max_length=50)),
                ('smtp_email', models.CharField(blank=True, max_length=50)),
                ('smtp_password', models.CharField(blank=True, max_length=10)),
                ('smtp_port', models.CharField(blank=True, max_length=5)),
                ('return_policy', ckeditor.fields.RichTextField(blank=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True)),
                ('cookie_policy', ckeditor.fields.RichTextField(blank=True)),
                ('store_announcements', ckeditor.fields.RichTextField(blank=True)),
                ('message_to_buyers', ckeditor.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
